- name: Deploy Dockerized App 
  hosts: web
  become: true
  tasks:

    - name: Copy Docker image tar to remote server
      copy:
        src: /root/project/webapp.tar
        dest: /root/webapp.tar

    - name: Load Docker image from tar
      command: docker load -i /root/webapp.tar


    - name: Run new container
      command: docker run -d -p 5000:5000 --name webapp webapp:latest
